services:
  backend:
    build: ./backend
    expose:
      - "3000"
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI:-mongodb://root:whdQdCaV2ySMYmHiKIC0Eydm5Mf3U3Rxl5OZuiFJsPc1l5TDKdfqFGCKWkVcAVNu@ac4ljene7dzemo5naoldrcmv:27017/?directConnection=true}
      - DB_NAME=${DB_NAME:-mongodb-database-ac4ljene7dzemo5naoldrcmv}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_DOMAIN=${ALLOWED_DOMAIN:-healthmaiscuidados.com}
      - JWT_SECRET=${JWT_SECRET:-coringa_secret_key}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_CLAIMS_EMAIL=${VAPID_CLAIMS_EMAIL}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
