default_operators = [
    {"name": "Unimed"},
    {"name": "Camperj"},
    {"name": "Particular"}
]

default_indicators = [
  {
    "name": "01 - Indicador de Fluxo Assistencial",
    "targetType": "PERCENTUAL",
    "targetDirection": "MAIOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "subindicators": [
      { "name": "1.1 - Alta Domiciliar", "targetType": "PERCENTUAL", "targetDirection": "MAIOR", "targetValue": 5 },
      { "name": "1.2 - Admissão", "targetType": "NÚMERICO", "targetDirection": "MAIOR", "targetValue": 0 }
    ]
  },
  {
    "name": "02 - Nº de Intercorrências",
    "targetType": "NÚMERICO",
    "targetDirection": "MENOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "subindicators": [
      { "name": "2.1 - Resolvidas em domicílio", "targetType": "NÚMERICO", "targetDirection": "MAIOR", "targetValue": 0 },
      { "name": "2.2 - Necessidade de Remoção APH", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 }
    ]
  },
  {
    "name": "03 - Taxa de Internação Hospitalar",
    "targetType": "PERCENTUAL",
    "targetDirection": "MENOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "subindicators": [
      { "name": "3.1 - Deterioração clínica", "targetType": "PERCENTUAL", "targetDirection": "MENOR", "targetValue": 0 },
      { "name": "3.2 - Não aderência ao tratamento", "targetType": "PERCENTUAL", "targetDirection": "MENOR", "targetValue": 0 }
    ]
  },
  {
    "name": "04 - Nº de óbitos",
    "targetType": "NÚMERICO",
    "targetDirection": "MENOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "subindicators": [
      { "name": "4.1 - Menos de 48 horas após implantação", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 },
      { "name": "4.2 - Mais de 48 horas de implantação", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 }
    ]
  },
  {
    "name": "05 - Taxa de Alterações de PAD",
    "targetType": "PERCENTUAL",
    "targetDirection": "MENOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "subindicators": [
      { "name": "5.1 - ↑ PAD", "targetType": "PERCENTUAL", "targetDirection": "MENOR", "targetValue": 0 },
      { "name": "5.2 - ↓ PAD", "targetType": "PERCENTUAL", "targetDirection": "MAIOR", "targetValue": 10 }
    ]
  },
  {
    "name": "06 - Quantitativo de pacientes AD e ID",
    "targetType": "NÚMERICO",
    "targetDirection": "MAIOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "subindicators": [
      { "name": "6.1 - AD (Atenção Domiciliar)", "targetType": "NÚMERICO", "targetDirection": "MAIOR", "targetValue": 0 },
      { "name": "6.2 - ID (Internação Domiciliar)", "targetType": "NÚMERICO", "targetDirection": "MAIOR", "targetValue": 0 }
    ]
  },
  {
    "name": "07 - Nº de pacientes infectados",
    "targetType": "PERCENTUAL",
    "targetDirection": "MENOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "observations": "INÍCIO DE USO DE ANTIBIÓTICO EM 48H, META 0%",
    "subindicators": [
      { "name": "7.1 - <48h Início de Antibiótico", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 },
      { "name": "7.2 - >48h Pós-Antibiótico", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 }
    ]
  },
  {
    "name": "08 - Nº de eventos adversos",
    "targetType": "NÚMERICO",
    "targetDirection": "MENOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "subindicators": [
      { "name": "8.1 - Quedas", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 },
      { "name": "8.2 - Broncoaspiração", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 },
      { "name": "8.3 - Lesão por pressão", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 },
      { "name": "8.4 - Decanulação", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 },
      { "name": "8.5 - Saída acidental da GTT", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 }
    ]
  },
  {
    "name": "09 - Nº de ouvidorias",
    "targetType": "NÚMERICO",
    "targetDirection": "MENOR",
    "targetValue": 0,
    "comparisonInterval": "ABSOLUTO",
    "subindicators": [
      { "name": "9.1 - Elogios", "targetType": "NÚMERICO", "targetDirection": "MAIOR", "targetValue": 0 },
      { "name": "9.2 - Sugestões", "targetType": "NÚMERICO", "targetDirection": "MAIOR", "targetValue": 0 },
      { "name": "9.3 - Reclamações e Solicitações", "targetType": "NÚMERICO", "targetDirection": "MENOR", "targetValue": 0 }
    ]
  }
]

default_patients = [
    "ALVARO JOSE DA SILVA MELO",
    "ANA CAROLINA MENDES NOGUEIRA GOMES",
    "ANGELA MARIA MENEZES DE LIMA",
    "ANIBAL GONCALVES ALVES",
    "BENEDIR DE OLIVEIRA GASPAR",
    "DAISY AMOEDO BARREIRA",
    "DANILO DOMINGUES DE CARVALHO FILHO",
    "DEA ARAUJO DE AZEVEDO",
    "EDISON SANTOS CORREA",
    "EDUARDO CARLOS CARDOSO",
    "ELZA GUDULA MARIA DELBAERE",
    "EVANDRO DE OLIVEIRA SILVA",
    "FABIO CAVALCANTI DE ALBUQUERQUE MASSA",
    "FERNANDO CABRAL GOMES",
    "GENEIR HOLOSBACK ROSSES",
    "HUGO GOLDEMBERG",
    "IDE CORREA CARDOSO",
    "IZA MARIA BASTOS VIANNA",
    "JANAINA MARQUES CORREA MELO",
    "JOAO BOSCO FLEURY",
    "KATIA COSTA MARQUES DE FARIA",
    "LAIS FERNANDES GARCIA",
    "LEONEL DOS SANTOS",
    "LUCIA HELENA DOS SANTOS LUSQUINOS RODRIGUES",
    "LUCIA NEVES OLIVEIRA",
    "LUIZ FERNANDO DA COSTA GOMES",
    "LUIZ MARIO ROSSES FILHO",
    "MARIA EDUARDA PACHECO NEVARES ALVES",
    "MARIA CRISTINA DA SILVA GAERTNER",
    "MARIA ELIANE GABRIEL ENNE",
    "MÁRCIA LEITE DE ABREU",
    "MARIA GONCALVES SOARES",
    "MARILEA BARROSO MAGALHAES",
    "NEIDE RODRIGUES",
    "NILDA MARIA BENEVIDES DE MIRANDA",
    "ODAIA ALVES DOS REIS",
    "OZELINA DE SOUZA BARROS",
    "PAULO OSCAR DE FARIAS",
    "RAMONA VIRGINIA ZACARIAS DE BECKERIG",
    "RUTE ELENA FERREIRA GOMES",
    "VERA MARIA FLORENCIO BERTO",
    "WANDA DE ALMEIDA VACITE",
    "VERA LUCIA FERREIRA TAROUQUELA",
    "ZENEIDA GAUDIE LEY LAGOEIRO DE MAGALHAES",
    "FERNANDO LÚCIO LAGOEIRO GUIMARÃES ABREU",
    "REGINA COELI TOSTES CALDAS",
    "RICARDO LUIZ DA SILVA REIS",
    "RUBINEIDE CAMPOS DOS REIS",
    "BEATRIZ RIBEIRO",
    "CLARISSE JEANNE OLIVEIRA DOS SANTOS",
    "DENIZAR QUEIROZ",
    "EMANUEL SOUZA MAIA",
    "GILDA HELOISA DE SOUZA LIMA",
    "ISABELLE OLIVEIRA ROSA",
    "JOAQUIM PAULO MATOS",
    "JOSE ABELARDO",
    "JOE DAMIÃO SESTELLO QUADROS",
    "LUCILIA DE CARVALHO GIMENEZ",
    "MARCIO LUIZ PISANI DE SOUZA",
    "MARIA ALICE SANTOS",
    "MARIA DE LOURDES DA SILVA SEMEDO",
    "MARIA BATISTA DA SILVA LIRA",
    "MARINA FELIX DE SOUZA",
    "REBECCA SIQUEIRA",
    "SIMONE DIAS",
    "ITAMAR CHAVES DURAO",
    "JOÉ DAMIÃO",
    "REBECCA SIQUEIRA ROSA",
    "CLEUZA TEIXEIRA DE ARAÚJO",
    "DENIZE DE SOUZA BOM",
    "JOÃO LACERDA PEREIRA",
    "JONAIR MACHADO DE ABREU",
    "JOSÉ ABELARDO SOUZA ANDRADE",
    "LENICE SALLES PEREIRA",
    "LUISA DO NASCIMENTO ELOI",
    "MARIA DA PENHA OLIVEIRA DE ALMEIDA",
    "MARIA DAS GRACAS DOS SANTOS SILVA",
    "MARIA DO CARMO LOURENÇO DA SILVA",
    "PEDRO PACHECO DE MATTOS",
    "SIMONE DIAS LOPES",
    "GEANETTE DOROTHEIA PIMENTEL DA SILVA",
    "WALDIR NUNES RIBEIRO",
    "MARIA EDUARDA PACHECO",
    "EVANDRO DE OLIVEIRA",
    "ALVARO JOSE",
    "ANA CAROLINA",
    "ANGELA MARIA",
    "ANIBAL GONÇALVES",
    "BENEDIR DE OLIVEIRA",
    "DAISY AMOEDO",
    "DANILO DOMINGUES",
    "DEA DE ARAUJO",
    "EDISON SANTOS",
    "EDUARDO CARLOS",
    "ELZA GUDULA",
    "FABIO CALVACANTI",
    "FERNANDO CABRAL",
    "FERNANDO LUCIO",
    "GENARIO BARBOSA",
    "GENEIR HOLOSBACK",
    "HUGO GOLDEMBERG",
    "IDE CORREA",
    "IZA MARIA",
    "JANAINA MARQUES",
    "JOAO BOSCO",
    "KATIA COSTA",
    "LAIS FERNANDES",
    "LUCIA HELENA",
    "LUCIA NEVES",
    "LUIZ FERNANDO",
    "LUIZ MARIO",
    "MARCIA LEITE",
    "MARIA CRISTINA",
    "MARIA ELIANE",
    "MARIA GONÇALVES",
    "MARILEA BARROSO",
    "MARINA BRASIL",
    "NILDA MARIA",
    "NILZA COELHO",
    "ODAIA ALVES",
    "OZELINA DE SOUZA",
    "PAULO OSCAR",
    "RAMONA VIRGINIA",
    "REGINA COELI",
    "RICARDO LUIZ",
    "RUBINEIDE CAMPOS",
    "RUTE ELENA",
    "VERA LUCIA",
    "VERA MARIA",
    "WANDA DE ALMEIDA",
    "ZENEIDA GAUDIE",
]
